document.addEventListener('DOMContentLoaded',function() {
    const grid=document.querySelector('.grid')
    const flagsLeft=document.querySelector('#flags_left')
    const result=document.querySelector('#result')
    const width=10
    let bombAmount=19
    let squares=[]
    let isGameOver=false
    let flags=0

    //create board
    
    function createBoard(){
        flagsLeft.innerHTML=bombAmount

        //get shuffled game array with random bombs
        
        const bombsArray=Array(bombAmount).fill('bomb')
        const emptyArr=Array(width*width-bombAmount).fill('valid')
        //combines bomb and empty spaces
        const gameArr=emptyArr.concat(bombsArray)
        //used to shuffle the array based on the randome number generated by the Math.random() function using the arrow function
        const shuffledArr= gameArr.sort(()=>Math.random()-0.5)
        //console.log(shuffledArr)

        for(let i=0;i<width*width;i++){
            const square=document.createElement("div")
            square.setAttribute('id',i)
            square.classList.add(shuffledArr[i])
            grid.appendChild(square)
            squares.push(square)

            //normal click
            square.addEventListener('click',function(){
                click(square)
            })
            //cntrl and left click
            square.addEventListener('contextmenu',function(){
               addFlag(square)
            })
            square.addEventListener('dblclick',function(){
                removeFlag(square)
            })
        
    }
    //add numbers
    for(let i=0;i<squares.length;i++){
        let total=0
        const isLeftEdge=(i%width===0)
        const isRightEdge=(i%width===width-1)

        if(squares[i].classList.contains('valid') ){
            //to check left
            console.log(squares.length)
            if(i>0 && !isLeftEdge && squares[i-1].classList.contains('bomb'))
            {
                total++}
                //to check top right
            if(i>9 && !isRightEdge && squares[i+1-width].classList.contains('bomb'))
            {
                total++
            }
            //to check top
            if(i>10 && squares[i-width].classList.contains('bomb'))
            {
                total++
            }
            //to check top left
            if(i>11 && squares[i-width-1].classList.contains('bomb') && !isLeftEdge)
            {
                total++
            }
            //to check right
            if(i<99 && squares[i+1].classList.contains('bomb') && !isRightEdge)
            {
                total++
            }
            //to check bottom left
            if(i<90 && squares[i+width-1].classList.contains('bomb') && !isLeftEdge)
            {
                total++
            }
            //to check bottom right
            if(i<88 && squares[i+width+1].classList.contains('bomb') && !isRightEdge)
            {
                total++
            }
            //to check bottom
            if(i<89 && squares[i+width].classList.contains('bomb') && !isRightEdge)
            {
                total++
            }
            //to set the total number of bombs near the square
            console.log(total)
            squares[i].setAttribute('data',total)
        }
    }
    }
    createBoard()

    //add flag with right click
    function addFlag(square){
        if (isGameOver) return
        if(!square.classList.contains('checked') && (flags<bombAmount)){
            if(!square.classList.contains('flag')){
                square.classList.add('flag')    
                flags++
                square.innerHTML='🚩'
                flagsLeft.innerHTML=bombAmount-flags
                checkForWin()
            }}
        
            
    }

    function removeFlag(square){
        if (isGameOver) return
        if(square.classList.contains('flag')){
            square.classList.remove('flag')
            square.innerHTML=''
            flags--
            flagsLeft.innerHTML=bombAmount-flags
        }
    }


    function click(square){
        console.log(square);
        if(isGameOver || square.classList.contains('checked') || square.classList.contains('flag')) 
        {
            return
        }

        if(square.classList.contains('bomb')) {
            gameOver()
        }
        else{
            let total=square.getAttribute('data')
            console.log(total)
            if(total!=0){
                if(total==1) square.classList.add('one')
                if(total==2) square.classList.add('two')
                if(total==3) square.classList.add('three')
                if(total==4) square.classList.add('four')
                console.log(total)
                square.innerHTML=total
                return
            }
            checkSquare(square)
        }
        square.classList.add('checked')
}
//check neighboring squares once square is clicked
    function checkSquare(square){
        const currentId=square.id
        const isLeftEdge=(square.id%width===0)
        const isRightEdge=(square.id%width===width-1)

        setTimeout(function (){
            if(currentId>0 && !isLeftEdge){
                const newId= parseInt(currentId)-1
                const newSquare=document.getElementById(newId)
                click(newSquare)
            }
            if(currentId>9 && !isRightEdge){
                const newId= parseInt(currentId)+1-width
                const newSquare=document.getElementById(newId)
                click(newSquare)
            }
            if(currentId>10){
                const newId=parseInt(currentId)-width
                const newSquare=document.getElementById(newId)
                click(newSquare)
            }
            if(currentId>11 && !isLeftEdge){
                const newId= parseInt(currentId)-1-width
                const newSquare=document.getElementById(newId)
                click(newSquare)
            }
            if(currentId<98 && !isRightEdge){
                const newId=parseInt(currentId)+1
                const newSquare=document.getElementById(newId)
                click(newSquare)
            }
            if(currentId<90 && !isLeftEdge){
                const newId= parseInt(currentId)-1+width
                const newSquare=document.getElementById(newId)
                click(newSquare)
            }
            if(currentId<88 && !isRightEdge){
                const newId= currentparseInt(currentId)+1+width
                const newSquare=document.getElementById(newId)
                click(newSquare)
            }
            if(currentId<89){
                const newId= parseInt(currentId)+width
                const newSquare=document.getElementById(newId)
                click(newSquare)
            }
        },10)
    }

    function checkForWin(){
        let matches=0
        for(let i=0;i<squares.length;i++){
            if(squares[i].classList.contains('flag') && squares[i].classList.contains('bomb')){
                matches++
            }
            if(matches===bombAmount){
                result.innerHTML='You Win!'
                isGameOver=true
            }
        }
    }

    function gameOver(){
        result.innerHTML='BOOM! Game Over!'
        isGameOver=true

        //show all the bombs
        squares.forEach(function(square){
            if(square.classList.contains('bomb')){
                if(square.classList.contains('bomb')){
                    square.innerHTML='💣'
                    square.classList.remove('bomb')
                    square.classList.add('checked')
                }
                
            }
        })
    }

});